import type { NextPage } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { GetStaticPaths, GetStaticProps } from 'next';
import Head from 'next/head';

import { createClient } from 'contentful';
import { formatBody, formatDate } from '../../utils/helpers';

import { IBlogPost } from '../../components/BlogPost';
import classes from '../../styles/Post.module.css';
import { fetchPaths, fetchPost } from '../../utils/contentful-post';

const Post: NextPage = ({ post }: any) => {
  return (
    <div className={classes.container}>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,600;1,400;1,600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <header>
        <h1 className={classes.title}>
          Welcome to the <Link href="/">Contenful Blog</Link>
        </h1>
      </header>

      <main className={classes.main}>
        <h1 className={classes['blog-post__title']}>{post.title}</h1>
        <div className={classes['blog-post__media-meta-wrapper']}>
          <div className={classes['blog-post__media']}>
            <Image src={post.featuredImageUrl} alt="" width="748" height="500" />
          </div>
          <div className={classes['blog-post__meta']}>
            <div className={classes['blog-post__meta-block']}>
              <p className={classes['blog-post__meta-title']}>Published</p>
              <p className={classes['blog-post__meta-content']}>{post.datePublished}</p>
            </div>
            <div className={classes['blog-post__meta-block']}>
              <p className={classes['blog-post__meta-title']}>Author</p>
              <p className={classes['blog-post__meta-content']}>{post.author}</p>
            </div>
            <div className={classes['blog-post__meta-block']}>
              <p className={classes['blog-post__meta-title']}>Category</p>
              <p className={classes['blog-post__meta-content']}>{post.categoryName}</p>
            </div>
          </div>
        </div>
        <div
          className={classes['blog-post__body']}
          dangerouslySetInnerHTML={{ __html: post.body }}
        />
      </main>
    </div>
  );
};

export const getStaticPaths: GetStaticPaths = async () => {
  const paths = await fetchPaths();

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }: any) => {
  const entry = await fetchPost(params);

  return {
    props: { post: entry },
  };
};

export default Post;
