import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';

import BlogSection from '../components/BlogSection';
import classes from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={classes.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,600;1,400;1,600&display=swap"
          rel="stylesheet"
        />
      </Head>

      <header>
        <h1 className={classes.title}>
          Welcome to the <Link href="/">Contenful Blog</Link>
        </h1>
      </header>

      <main className={classes.main}>
        <BlogSection limit={4} variation="featured" />
        <BlogSection title="Most Popular" limit={6} variation="grid" />
        <BlogSection
          title="Browse All"
          limit={3}
          variation="grid"
          dropdown={true}
          loadOnDemand={true}
        />
      </main>
    </div>
  );
};

export default Home;
